app = "coded-a"  # Replace this later in Fly UI

[env]
  PASSWORD = "changeme123"  # Replace this with a secure password

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
